name: bash-completion

on:
  workflow_dispatch:
    inputs:
      SHA:
        description: "SHA under test"
        required: true
  pull_request:
    paths:
      - '.github/workflows/bash-completion.yaml'
      - 'bash-completion/bpftool'
      - 'libbpf/**'
      - 'src/**'
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  bash-completion:
    name: Bash completion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: 'bpftool'
          submodules: recursive
          ref: ${{ inputs.SHA || github.sha }}

      - name: Checkout bash-completion repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: 'scop/bash-completion'
          ref: '81b0f8c4dfafd6219c95ffa1defad7ff34394b0f' # v2.13.0
          path: 'bash-completion'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libbpf-dev libelf-dev llvm

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install pytest pytest-xdist psutil

      - name: Build and install bpftool
        working-directory: 'bpftool'
        run: |
          sudo CLANG='/usr/bin/false' LLVM_CONFIG="$CLANG" \
              make -j -C src install

      #- name: Build and load sample BPF program, map
      #  working-directory: '/tmp'
      #  run: |
      #    cat > test.c << EOF
      #    #include <linux/bpf.h>
      #    #include <bpf/bpf_helpers.h>

      #    struct {
      #    	__uint(type, BPF_MAP_TYPE_ARRAY);
      #    	__type(key, __u32);
      #    	__type(value, __u32);
      #    	__uint(max_entries, 1);
      #    } bash_comp_map SEC(".maps");

      #    int bash_comp_test(__attribute__((unused)) void *ctx)
      #    {
      #    	__u32 key = 0;
      #    	__u32 *value;

      #    	value = bpf_map_lookup_elem(&bash_comp_map, &key);
      #    	if (!value)
      #    		return 0;

      #    	return *value;
      #    }
      #    EOF
      #    cat test.c
      #    clang -g -O2 -emit-llvm -c test.c -o - | \
      #        llc -march=bpf -filetype=obj -o test.o
      #    sudo bpftool prog load test.o /sys/fs/bpf/bash-completion-test type xdp
      #    sudo bpftool prog list
      #    sudo bpftool map list

      - name: Move Bash completion files to bash-completion repository
        run: |
          mv -t bash-completion/completions/ bpftool/bash-completion/bpftool
          mv -t bash-completion/test/t/      bpftool/scripts/test_bpftool.py
          # Shorten timeout (defaults to 30), too long to debug CI
          sed -i '/bash.expect(/,/]$/ s/]$/] , timeout=3/' \
              bash-completion/test/t/conftest.py

      - name: Run Bash completion tests
        working-directory: 'bash-completion'
        run: |
          sudo PYTHONDONTWRITEBYTECODE=1 \
              pytest -n auto --color=yes -vv test/t/test_bpftool.py
